### PR TITLE
WIP: Feature/epel repo

### PR DESCRIPTION
**Pull request by proffalken**

### CODE REVIEW

**Comment by christiangda** [comment]
Hi @proffalken as soon I have time I will check it and merge

**Comment by proffalken** [comment]
@christiangda leave it for now, I'll mark it as WIP, I hadn't realised that I'd left the collectd stuff uncommented...

**Comment by christiangda** [comment]
@proffalken I saw your pull request, will add the conditional 
```

dependencies:
  - {
      role: christiangda.epel_repo,
      when: ansible_os_family == 'RedHat' and cwa_use_epel_role,
    }
``` 

instead of 

```
{ role: christiangda.epel_repo, when: cwa_use_epel_role|bool }
```

Why have you cast boolean variables always? Are you having problems? what platform? OS, etc?.  my test in vagrant doesn't reflect any warning or error and I tested it many versions of ansible and python and OS as you can see in travis.ci (https://travis-ci.org/christiangda/ansible-role-amazon-inspector-agent)

**Comment by proffalken** [comment]
@christiangda "boots and braces" approach to this, I prefer to be explicit about these things, but if it works without then please feel free to remove.

**Pull request closed without merging**
